export const state = () => ({
  officeName_id: '',
  officeName: '',
  CEOName_id: '',
  CEOName: '',
  postalCode_id: '',
  postalCode: '',
  addressOne_id: '',
  addressOne: '',
  addressTwo_id: '',
  addressTwo: '',
  telNumber_id: '',
  telNumber: '',
  faxNumber_id: '',
  faxNumber: '',
  officeUrl_id: '',
  officeUrl: '',
  fileName_id: '',
  fileName: '',
  consumptionTax_id: '',
  consumptionTaxVal: '',
  consumptionTaxRounding_id: '',
  consumptionTaxRoundingVal: '',
  mulUnitPriceQuantityRounding_id: '',
  mulUnitPriceQuantityRoundingVal: '',
  unitPriceCulculationRounding_id: '',
  unitPriceCulculationRoundingVal: '',
  decimalalPart_id: '',
  decimalalPartVal: '',
  numberOfDigits_id: '',
  numberOfDigitsVal: '',
  amountOfWithholdingTax_id: '',
  amountOfWithholdingTaxVal: '',
  text_id: '',
  textVal: '',
  taxRate_id: '',
  taxRateVal: '',
  salaryPaymentDate_id: '',
  salaryPaymentDateVal: '',
  bonusPaymentDate_id: '',
  bonusPaymentDateVal: '',
  logo_id: '',
  select_logo: '',
  seal_id: '',
  select_seal: '',
  check_id: '',
  disabled: false,
  numberbox_id: '',
  RegistrationNumberBox_val: false,
});

export const mutations = {
  set(state, companyData) {
    Object.keys(companyData).forEach((key) => {
      state[key] = companyData[key];
    });
  },
};
