export const state = () => ({
  responsible_id: '',
  responsible: '',
  customer_id: '',
  customer: '',
  nameKana_id: '',
  nameKana: '',
  textShort_id: '',
  textShort: '',
  textMemo_id: '',
  textMemo: '',
  serchkeyone_id: '',
  serchkeyone: '',
  serchkeytwo_id: '',
  serchkeytwo: '',
  check_id: '',
  check: false,
  postalcode: '',
  postalcode_id: '',
  address: '',
  address_id: '',
  post_id: '',
  post: '',
  department_id: '',
  department: '',
  manager_id: '',
  manager: '',
  honorific_id: '',
  honorific: '',
  phonenumber_id: '',
  phonenumber: '',
  emailinput_id: '',
  emailinput: '',
  telnumber_id: '',
  telnumber: 0,
  faxnumber_id: '',
  faxnumber: 0,
  transaction_id: '',
  transaction: '',
  tax_id: '',
  tax: '',
  deposit_id: '',
  deposit: '',
  collectmonth_id: '',
  collectmonth: '',
  collectday_id: '',
  collectday: '',
  balance_id: '',
  balance: '',
  betting_id: '',
  betting: '',
  category_id: '',
  category: '',
  taxrounding_id: '',
  taxrounding: '',
  pricerounding_id: '',
  pricerounding: '',
  pricecalc_id: '',
  pricecalc: '',
  taxcheck_id: '',
  taxcheck: false,
  financialname_id: '',
  financialname: '',
  branchname_id: '',
  branchname: '',
  accountnumber_id: '',
  accountnumber: '',
  accountname_id: '',
  accountname: '',
  depositcategory_id: '',
  depositcategory: '',
  keyone_id: '',
  keyone: '',
  keytwo_id: '',
  keytwo: '',
  memobox_id: '',
  memobox: '',
  defaultvalue_id: '',
  defaultvalue: false,
  inputcandidate_id: '',
  inputcandidate: false,
});

export const mutations = {
  set(state, companyData) {
    Object.keys(companyData).forEach((key) => {
      state[key] = companyData[key];
    });
  },
};
