export const state = () => ({
  // 顧客先情報
  taxProcess_id: '',
  taxProcess: '',
  issuance_id: '',
  issuance: '',
  address_id: '',
  address: '',
  addressForm_id: '',
  addressForm: '',
  corporationName_id: '',
  corporationName: '',
  departmentName_id: '',
  departmentName: '',
  divisionName_id: '',
  divisionName: '',
  positionName_id: '',
  positionName: '',
  staffName_id: '',
  staffName: '',
  honorific_id: '',
  honorific: '',
  tellNumber_id: '',
  tellNumber: '',
  faxNumber_id: '',
  faxNumber: '',
  //自社情報
  payment_id: '',
  payment: '',
  collectionDate_id: '',
  collectionDate: '',
  slipNumber_id: '',
  slipNumber: '',
  date_id: '',
  date: '',
  serial_id: '',
  serial: '',
  personName_id: '',
  personName: '',
  totalAmount_id: '',
  totalAmount: '',
  info1_id: '',
  info1: '',
  info2_id: '',
  info2: '',
  info3_id: '',
  info3: '',
  // 編集画面
  totalAm_id: '',
  totalAm: '',
  taxAmount_id: '',
  taxAmount: '',
  dayStart_id: '',
  dayStart: '',
  dayEnd_id: '',
  dayEnd: '',
  textEditer_id: '',
  textEditer: '',
});

export const mutations = {
  set(state, companyData) {
    Object.keys(companyData).forEach((key) => {
      state[key] = companyData[key];
    });
  },
};
