export const state = () => ({
  // 顧客先情報
  taxProcess_id: '',
  taxProcess: '',
  issuance_id: '',
  issuance: '',
  address_id: '',
  address: '',
  addressForm_id: '',
  addressForm: '',
  corporationName_id: '',
  corporationName: '',
  departmentName_id: '',
  departmentName: '',
  divisionName_id: '',
  divisionName: '',
  positionName_id: '',
  positionName: '',
  staffName_id: '',
  staffName: '',
  honorific_id: '',
  honorific: '',
  tellNumber_id: '',
  tellNumber: '',
  faxNumber_id: '',
  faxNumber: '',
  project_id: '',
  project: '',
  //自社情報
  payment_id: '',
  payment: '',
  collectionDate_id: '',
  collectionDate: '',
  slipNumber_id: '',
  slipNumber: '',
  date_id: '',
  date: '',
  serial_id: '',
  serial: '',
  personName_id: '',
  personName: '',
  totalAmount_id: '',
  totalAmount: '',
  deliveryDeadline_id: '',
  deliveryDeadline: '',
  deliveryPlace_id: '',
  deliveryPlace: '',
  transactionSystem_id: '',
  transactionSystem: '',
  dateExpiry_id: '',
  dateExpiry: '',
  // 編集画面
  totalAm_id: '',
  totalAm: '',
  taxAmount_id: '',
  taxAmount: '',
  dayStart_id: '',
  dayStart: '',
  dayEnd_id: '',
  dayEnd: '',
  productcode_id: '',
  productcode: '',
  productname_id: '',
  productname: '',
  quanitity_id: '',
  quanitity: '',
  unit_in_id: '',
  unit_in: '',
  unitprice_id: '',
  unitprice: '',
  remarks_id: '',
  remarks: '',
  tax_in_id: '',
  tax_in: '',
});

export const mutations = {
  set(state, companyData) {
    Object.keys(companyData).forEach((key) => {
      state[key] = companyData[key];
    });
  },
};
